import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {ChevronDown, Calendar, Home, Menu} from 'lucide-react'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Schedule for DS90",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <div className="fixed left-0 right-0 bottom-0 mx-auto w-[350px] h-16 bg-white rounded-t-3xl shadow flex items-center justify-around">
          <button className="text-gray-400 hover:text-gray-900">
            <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <circle cx="12" cy="12" r="10" strokeWidth="2" />
            </svg>
          </button>
          <button className="text-orange-500">
            <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path d="M21 21l-4.35-4.35" strokeWidth="2" />
            </svg>
          </button>
          <button className="relative text-gray-400 hover:text-gray-900">
            <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <circle cx="12" cy="12" r="10" strokeWidth="2" />
            </svg>
            <span className="absolute -top-1 -right-1 bg-orange-500 text-white text-xs px-1 rounded-full">3</span>
          </button>
          <button className="text-gray-400 hover:text-gray-900">
            <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <circle cx="12" cy="12" r="10" strokeWidth="2" />
            </svg>
          </button>
        </div> */}
      </body>
    </html>
  );
}