import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {ChevronDown, Calendar, Home, Menu} from 'lucide-react'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <div>
    <div className="bg-gradient-to-r from-purple-600 to-pink-500 text-white p-6 rounded-b-3xl shadow-lg">
        <h1 className="text-2xl font-semibold">Schedule</h1>
    </div> 
  </div>
        {children}
      </body>
    </html>
  );
}
